//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginWebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {

        public int UserID { get; set; }
        [DisplayName("Username")]
        [Required(ErrorMessage = " This field is empty")]
        public string UserName { get; set; }
        [DisplayName("Password")]
        [Required(ErrorMessage = " This field is empty")]
        public string Password { get; set; }
        [DisplayName("Image")]
        [Required(ErrorMessage = " This field is empty")]
        public byte[] Imagine { get; set; }

        public string RemoveErrorMessage;
        public string RegisterErrorMessage;
        public string LoginErrorMessage;
        public string EditErrorMessage;
    }
}
